### PR TITLE
Fix:Changed hyphenation frequency to none.

### PR DESCRIPTION
**Pull request by ashu-dadhich**
PR for issue #329 
Change:

- added an attribute android:hyphenationFrequency so that email in Office of victim advocasy and office of inspector general in get help now section could be shown corectly.

### CODE REVIEW

**Comment by sandarumk** [comment]
One more place I missed earlier. Can you confirm whether this works for API versions before API level 23?

**Comment by ashu-dadhich** [comment]
Yeah sure.
Will get back to you after checking it.

**Comment by ashu-dadhich** [comment]
I am sorry it doesn't. 
**The applications lower than api 23 would simply ignore it but it won't cause any error**

Two other possible alternatives:

- Encode the the string in different format like \u00A0

- Use  a separate algorithm for it.

**Comment by sandarumk** [comment]
I think we should rest the problem here because we are wasting time on this.

**Comment by ashu-dadhich** [comment]
ok.

**Pull request closed without merging**
