### PR TITLE
Implemented change location as in mockup

### LINKED ISSUE #136: Implement 'Change Location' as in mockup
The drop down can be made similar to the one in mockup
Also, we can add (current post) as given in mockup "This is information for Uganda (current post)"

screenshot_2016-03-10-01-28-32_com peacecorps pcsa

screenshot 505

### PR DESCRIPTION
**Pull request by AkankshaBodhankar**
Added a dropdown icon and a border
Also, added (current post) 
Resolved #136 

screenshot_2016-04-12-23-13-35_com peacecorps pcsa

### CODE REVIEW

**Comment by Buddhiprabha** [comment]
@AkankshaBodhankar as discussed on the issue, a white border is required

**Comment by Buddhiprabha** [comment]
@AkankshaBodhankar as discussed on the issue, a white border is required

**Comment by AkankshaBodhankar** [comment]
@Buddhiprabha does this look fine?
I'll change the code and commit the files if this is okay

screenshot_2016-04-13-09-14-07_com peacecorps pcsa

**Comment by AkankshaBodhankar** [comment]
or this 
screenshot_2016-04-13-09-19-37_com peacecorps pcsa

**Comment by Buddhiprabha** [comment]
@AkankshaBodhankar The same look and feel of a button is preferred. i.e. A white border with a background color similar to that of button. With letters (eg. the text "Tunisia") in white. Can you please change accordingly?

**Comment by AkankshaBodhankar** [comment]
@Buddhiprabha Will the design according to that

**Comment by AkankshaBodhankar** [comment]
Sending a new PR with changes made

**Pull request closed without merging**
