### PR TITLE
Overdraw fixed.

### PR DESCRIPTION
**Pull request by m-murad**
Solves issue #371 

@sandarumk please review.

### CODE REVIEW

**Comment by m-murad** [comment]
@sandarumk
Please review and merge.

**Comment by sandarumk** [comment]
This is a lint issue right?

**Comment by m-murad** [comment]
No

**Comment by m-murad** [comment]
@sandarumk 
Sorry, yes it is.

**Comment by sandarumk** [comment]
It is okay since it is the first time. But please refrain from duplicating issues. If the lint issue list is outdated simply put a new list there.

**Comment by chamika** [comment]
+1

**Pull request merged**
