### PR TITLE
Issue #367 Multiple instances of fragment when clicked from navigation drawer resolved.

### PR DESCRIPTION
**Pull request by harshitagupta30**
Fixes Issue #367 
@sandarumk Please review the PR and let me know if any changes are required.

### CODE REVIEW

**Comment by harshitagupta30** [comment]
videotogif_2017 02 11_15 14 13

**Comment by ashu-dadhich** [comment]
Hi @harshitagupta30 I suggest you give a link of the issue as it is easy for mentors to refer your pr.
eg. "PR for #367"

**Comment by harshitagupta30** [comment]
@top-gun007 Thanks for suggestion! I have updated my earlier comment!

**Comment by chamika** [comment]
+1

**Pull request merged**
