### PR TITLE
Issue 276

### PR DESCRIPTION
**Pull request by riddhik84**
Implemented:
- All country names on login screen 
- Get help now buttons dial numbers for PCMO, SSM and SARL as per country selected 
- If country is changed after login, Get help now will update accordingly. 
- If number is not present for PCMO, SSM or SARL, the button will be disabled.

### CODE REVIEW

**Comment by sandarumk** [comment]
Please remove the merge commits and other commits from the PR. Seems like you haven't rebase your branch.

**Comment by riddhik84** [comment]
I tried to find out how to remove it but not much success doing it. Could you help me how to do that?

**Comment by m-murad** [comment]
@riddhik84 
You need to fetch the latest changes from upstream.
Update your branches from upstream.
Then make changes locally.
The force push the branch.

Please follow these steps
1. Checkout your `develop` branch `git checkout develop`
2. Fetch updates using `git fetch upstream`
3. Rebase your local branch using `git rebase upstream/develop`
4. Force push the updated branch to your repository `git push --force origin develop`

Then you can start working on the issue.

**Comment by riddhik84** [comment]
So I have already implemented fix for the issue as branch 'issue_276'. Do I need to implement it again?

**Comment by m-murad** [comment]
@riddhik84 
I am afraid you have to.
But you can take help from the previous changes you have made.
https://github.com/systers/FirstAide-Android/pull/374/files

**Comment by m-murad** [comment]
Its better you delete this branch locally and create the branch again with exact same name.

**Comment by codingblazer** [comment]
@riddhik84 Hey
You don't need to re implement them again. Just Do the following -
git checkout issue_276
git fetch upstream
git rebase upstream/develop
git push -f origin issue_276

**Comment by codingblazer** [comment]
@free4murad Even if she need to create new branch, there is no need to reimplement it. She can just undo her commit and stash all her work and pop it on updated branch.
@riddhik84 Tell us if you get stuck anywhere.

**Comment by riddhik84** [comment]
ok tried to play around above suggestions but now having different issue:

[issue_276]> git push origin issue_276
To https://github.com/riddhik84/PCSA-Android.git
 ! [rejected]        issue_276 -> issue_276 (non-fast-forward)
error: failed to push some refs to 'https://github.com/riddhik84/PCSA-Android.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by m-murad** [comment]
Use force push

**Comment by codingblazer** [comment]
@riddhik84 You missed the -f in the solution I posted.

**Comment by m-murad** [comment]
git push --force origin issue_276

**Comment by riddhik84** [comment]
Ok.. worked now.. but my latest commit shows only one file while my original commit has 6 files. Is that also expected? Or I really now need to make all changes again?

**Comment by codingblazer** [comment]
@riddhik84 Its done. I can see 6 files above in your commit. 
I guess @sandarumk would review now. Thanks.

**Comment by riddhik84** [comment]
Thanks a lot for help!!

**Comment by codingblazer** [comment]
@riddhik84 Your latest commit is this because of which you are seeing 1 file.
https://github.com/systers/FirstAide-Android/pull/374/commits/76e5823647541a9979d9ea55acdf6f91f431f553

**Comment by codingblazer** [comment]
@riddhik84 You should also squash your commits (combine last 3 commits into one). But wait for @sandarumk for further instructions/review.

git checkout issue_276   
git reset --soft HEAD~3     (undo your last 3 commits)
git commit -m 'Your commit message'  (make a new single commit instead)
git push -f origin issue_276   (force push)

**Comment by sandarumk** [comment]
You could have made a new branch, rebase it with upstream and cherry pick your commit and apply it to your new branch. Still your PR has three commits including an unnecessary commit which shouldn't be here.

**Comment by sandarumk** [comment]
One more thing, please use meaningful commit messages and refrain from using commit messages like updated and implementation.

**Pull request closed without merging**
