### PR TITLE
Reporting steps Implemented as in mockup

### LINKED ISSUE #26: Implement Reporting Steps as in Mockup
@sandarumk I went through the mockup provided and would like to implement the reporting steps page in the way described. Should I start working on that?

### PR DESCRIPTION
**Pull request by chhavip**
Fixes #26. @rosariorobinson @sandarumk , please review

### CODE REVIEW

**Comment by sandarumk** [comment]
@chhavip Can you please put the screen shots of your development.

**Comment by chhavip** [comment]
Here are the screenshots similar to as indicated in mockup:
screenshot_2016-02-10-10-51-50
screenshot_2016-02-10-10-51-55
screenshot_2016-02-10-10-52-05

They scroll horizontally on the device.

**Comment by sandarumk** [comment]
Hi Chavi,
The design has been updated. We will update the mock up with the latest design. I will start reviewing this after the new documents are in place. Then I can suggest if any changes to this section is required.
Dinu

**Comment by sandarumk** [comment]
The design changed to the vertical one we previously had. Closing the PR.

**Pull request closed without merging**
