### PR TITLE
Fix:bullet-issues resolved

### PR DESCRIPTION
**Pull request by ashu-dadhich**
PR for #344 
Changes:

- removed O from from "what is burglar" in Burglary glossary.
image

- Added "FACT:" instead of just ":"
image

- Made was is sexual assault page according to mock up.
screenshot_20170127-175348

- Made the text bold as was mentioned.
screenshot_20170127-175333

- Put text or call the volunteer in next line.
screenshot_20170127-175258

- Made "Char of sexual assault" just like "Tactics of ...."  
screenshot_20170127-175243

- Removed unnecessery full stop from one of the points.
screenshot_20170127-175415

### CODE REVIEW

**Comment by ashu-dadhich** [comment]
https://drive.google.com/open?id=0B23GILTwqWqCS1VaOVl2a0pXRms

**Comment by ashu-dadhich** [comment]
Sorry I accidentally closed it.

**Comment by sandarumk** [comment]
Since there are only 7 images, can you post them here rather than in a google doc?

**Comment by ashu-dadhich** [comment]
image posted

**Pull request merged**
