### PR TITLE
Hard Coded Numbers Changed GCI

### PR DESCRIPTION
**Pull request by dynamoAakash**
Submitted in completion of GCI task to fix hard coded strings. Let me know if changes are required.

### CODE REVIEW

**Comment by sandarumk** [comment]
@dynamoAakash Good call on removing the app.iml file. Can you please fix the merge conflicts in this CR. I hope those happened because the recent merge of a previously done PR of another student.
@calistus When Akash fix the merge conflicts, please check and put a +1 as comment if this is ready to merge and tag me or rose.

**Comment by dynamoAakash** [comment]
I am not sure how the conflicts showed up as they were not there when I submitted the pull request, also how to remove them?

**Comment by sandarumk** [comment]
It is because there was an earlier pull request which is merged after you submitted this PR. Typically to solve this kind of error you have to update your repo to the latest and solve them in your forked repo. I went through your code. It seems like that the merged pull request contained the same improvements that you made. So please keep this for now. I will talk with @calistus and see what can be done.

**Comment by dynamoAakash** [comment]
Yes, I know that earlier pull request contained the same improvements which
I also mentioned as a comment on GCI site. Let me know if I have to do
anything else for the task.

**Comment by sandarumk** [comment]
@dynamoAakash That should be decided by the mentor of the task. In this case @calistus .

**Comment by sandarumk** [comment]
Closing because the functionality is already added by an earlier pull request.

**Pull request closed without merging**
