### PR TITLE
Fixed name validation in Signup and UserSettings activity.

### PR DESCRIPTION
**Pull request by m-murad**
Fixed issue #297 and #296.
The user can no longer leave the name blank.

### CODE REVIEW

**Comment by rohands** [comment]
@free4murad what all validation checks are you performing?
I suggest you use <code>android:inputType="textPersonName|textCapWords"
</code>
This is just an example, set the required flags already available.

**Comment by free4murad** [comment]
Sorry didn't get your point.
How and where do I use flags.

Actually I am new to GitHub

**Comment by rohands** [comment]
@free4murad 
This is not related to GitHub. Your PR says "Fixed name validation in Signup and UserSettings activity". So I wanted to check if you have performed other checks apart from just checking if it's blank. Maybe inclusion of numbers also doesn't make sense for a name. So Android allows you to validate what the user types into the EditText by setting the property  <code>android:inputType</code>. The flags I am talking about are <b>textPersonName</b> and <b>textCapWords</b>. By setting the required flags you can perform a better validation with lesser code. This was what I was trying to explain

**Comment by free4murad** [comment]
@rohands 
got your point. I thought you are tell me about some PR syntax.

Actually my code is just checking if the name is empty or just some spaces.
If it's either of them its asks for a new input or does not change the already existing data.

If you want me to add more checks I can do that.
Should I insert checks for numbers and special characters?

**Comment by rohands** [comment]
@free4murad the framework already allows you to perform those checks by just adding a line of code in the XML file under the desired View. Why would you want to unnecessarily perform checks? 
You would want to look into the docs for <code>android:inputType</code> property.

**Comment by free4murad** [comment]
@rohands 
even if i use the property `android:inputType="textPersonName|textCapWords"`
the text fields will still accept special characters and numbers.

**Comment by rohands** [comment]
@free4murad That was an example trying to explain what you should do. Please do check the necessary docs and look for the flags which need to be set. In case there are none of them, leave a short note on why it's not possible. And then you can proceed with the programmatic validation that you are currently performing

**Comment by free4murad** [comment]
i applied the properties but it is still accepting special characters and numbers.

**Comment by free4murad** [comment]
@rohands 
ok thanks.
I will make a PR in which the name should not have numbers and special characters.
anything else???

**Comment by sandarumk** [comment]
@free4murad The commit for checking the empty string is okay. Please add the special character and number validation to the same PR so I can check and merge.

**Comment by m-murad** [comment]
@sandarumk 
will send a pr in a day if that is fine.

**Comment by m-murad** [comment]
@sandarumk 
The name validation is complete. I would like to highlight the functionalities

1. The text fields will only accept alphabetical characters and spaces.

2. If the user leaves the name empty or enters just spaces, an appropriate toast will appear.

3. If the user enters a number or a special symbol, an appropriate toast will appear.

4. Also if the user enters multiple spaces in between words the spaces will be reduced as one space. eg
If user enters - M  `  ` ` ` ` ` Murad
The app will interpret it as - M Murad

5. The same rules are followed in settings activity while changing the name.

**Comment by Buddhiprabha** [comment]
@free4murad commits related to one issue should ideally be squashed into one commit.

**Comment by sandarumk** [comment]
On top of @Buddhiprabha's comment, you should also use meaningful commit messages.  For the two commits, since the issue only talks about the empty string and we have asked for the second commit for other type validations it is okay and I will commit it before squashing. Your commit messages ideally have been things like "Added empty string validation".  Please read the PR best practices in the wiki to have a better idea.

**Pull request merged**
