### PR TITLE
Dialog Box UI has been implemented as in mockup. 

### PR DESCRIPTION
**Pull request by rohands**
Refractored all hardcoded elements and checked out to a new branch. 
Fresh PR made as mentioned by @sandarumk

### CODE REVIEW

**Comment by rohands** [comment]
@sandarumk 
Seems like the earlier commits have been restored on switching the branch, would there be any way to undo them?

**Comment by sandarumk** [comment]
Checking out a branch is not what I expected, because as you can see it will end in the same state with several commits for small changes. Ty whether this works https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by rohands** [comment]
@sandarumk 
There was a problem squashing the first commit, earlier 7 commits have been successfully squashed.

**Comment by rohands** [comment]
@sandarumk  Please give me some time to fix this Squashing issue, thank you

**Comment by sandarumk** [comment]
It's ok. Take your time.

**Pull request closed without merging**
