### PR TITLE
Fix:Added Missing commit() on SharedPreference editor with refrence to lint issues #222

### PR DESCRIPTION
**Pull request by top-gun007**
issue:Added Missing commit() on SharedPreference editor 
-   used apply() instead of commit(){Shared Pref} in CirlceIntro.java
- made no changes in CircleOfTrustFragment.java , Trustees.java, & SignupActivity.java as already found commit() in the following

### CODE REVIEW

**Comment by top-gun007** [comment]
@sandarumk please review it.

**Comment by sandarumk** [comment]
When you are naming the PR it is better to add what you did as the title rather than a generic one as "Fix lint issues"

**Comment by top-gun007** [comment]
hope its ok now @sandarumk.

**Comment by top-gun007** [comment]
and if its ok I would like to work on the remaining issues as well. Can i @sandarumk

**Comment by sandarumk** [comment]
Even though the issue is missing commit(), what you have done is replacing commit () with apply(). When adding PR title and commit, do mind about that without blindly adding lint issue title.

**Comment by top-gun007** [comment]
sorry about that @sandarumk will keep that in mind.

**Pull request merged**
