### PR TITLE
Added functionality to avoid duplicate comrade numbers 

### PR DESCRIPTION
**Pull request by AkankshaBodhankar**
Changes made as duplicate error message and removed conflicts from #112

### CODE REVIEW

**Comment by sandarumk** [comment]
Please useful meaningful commit messages. (https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message).

**Comment by AkankshaBodhankar** [comment]
Okay I'll keep that in mind

**Comment by AkankshaBodhankar** [comment]
Should I change it and make another PR for it because I'm unable to edit the commit messages now

**Comment by sandarumk** [comment]
Yeah sure. But if you wait until Rohan's PR is merged, it will help you to have the PR with no conflicts.

**Comment by sandarumk** [comment]
The said PR is merged. You can go ahead with this.

**Comment by AkankshaBodhankar** [comment]
#130 made a PR

**Pull request closed without merging**
