### PR TITLE
Removed hardcoded strings,colors,integers and dimensions (Issue #40)

### PR DESCRIPTION
**Pull request by yatna**
As said in the issue, hardcoding is not considered as a good practise. Thus colors have been put into colors.xml, integers into integer.xml, dimensions into dimens.xml and strings into strings.xml.

### CODE REVIEW

**Comment by sandarumk** [comment]
Hi Yatna, This seems fine. But rather than replacing 10 with "ten" can't you find a more common ground for the integers and dimensions. Like instead of @dimen/ten you can use like "text_view_padding_dimen".  The whole point of having these separately is the easier of access and change. So can you please go through this again and try to replace these with more meaningful names. I can see that you have done that for most of the integers and dimensions. Please try to replace the rest too. If you can't find any common names for these, please let me know.

**Comment by yatna** [comment]
Yes, I will take care of that :-) . In fact, in the starting I was doing it the correct way. But then there were places where for e.g 10 has been used for textView padding as well as for layout margin . So , I could not come up with a common name. 
Can I create 2 different dimens for the above example both with value 10 ? Or should I try to find a common name (though this will be difficult as the same numeric is sometimes used for various totally different things.)

**Comment by sandarumk** [comment]
Yes. You can use two different names. Since you are calling the name , not the other way around this won't be a problem. for example you can use 10 as text view padding and layout margin. But you can't use text view padding as 10 and 12. I think you got the point?

**Comment by yatna** [comment]
Yeah, I got it. :)
I will amend the previous commits.

**Comment by yatna** [comment]
Hi Sandarumk , as suggested I replaced the dimen names to more meaningful names.

**Comment by yatna** [comment]
New PR sent #83 after resolving merge conflicts.

**Comment by sandarumk** [comment]
Merged the new PR

**Pull request closed without merging**
