### PR TITLE
App logo updated

### PR DESCRIPTION
**Pull request by rohands**
The text following the logo has been modified to suit the requirements. **Peace Corps** has been changed to **First Aide**

screenshot_20160713-102744

### CODE REVIEW

**Comment by Buddhiprabha** [comment]
@rohands Just a quick question, is this the updated logo sent to you?

**Comment by rohands** [comment]
Yes

**Comment by rohands** [comment]
@Buddhiprabha Check the mailing list, Sandi has sent an image and asked me to change the text Peace Corps to First Aide

**Comment by Buddhiprabha** [comment]
@rohands Okay, I did not see the mail. Good work.

**Comment by rohands** [comment]
@Buddhiprabha I just noticed that Sandi has missed out everyone while replying in the mailing list except   me. Will re-post it to everyone next time

**Comment by calistus** [comment]
Forward the email to us so that all of us can be on the same page

**Comment by rohands** [comment]
Sure

**Pull request merged**
