### PR TITLE
Change no-trustee default text

### PR DESCRIPTION
**Pull request by agentCadmium**

### CODE REVIEW

**Comment by sandarumk** [comment]
@kisaacs Before you merge any pull request please read the wiki on the guidelines to review and merge code. The base branch for this PR has been the master branch. Hence it contains all the unnecessary commits which merge the develop to master. We don't merge those commits into master again.

**Comment by sandarumk** [comment]
@agentCadmium In android repositories there are certain files which should not be committed such as app.iml file. A quick Google Search will show you what to commit and what not to commit. Please read the READ ME and guidelines on how to submit a proper PR. For example, if you are submitting a PR about a UI change you have to at least add a screenshot of the change for the ease of reviewing and tracking. It is better to start with reporting an issue first. Please go through the mockup and adhere to that since that is what is approved by peace corps.

**Comment by kisaacs** [comment]
Sorry about that. I should have caught the develop/master issue when I was helping everyone get set up.

These PRs come from GHC OSD. We asked about the README re: reporting issues first but @MeepyMay told us we could move forward.

**Comment by sandarumk** [comment]
READ ME had the PR best practices part as well. It is okay to skip the reporting issue part since it is OSD. But atleast you should have followed the PR best practices and reviewing part and the adhere to the mockup to have a better idea of what Peace Corps wanted from the application. The Peace corps specifically ask the text to be Name. I am going to revert this. Unfortunately this can't be reverted automatically because there is one PR merged after this and it is re opened again. Hence I can't revert that PR and continue on reverting this.  So I have to do that manually from the command line.

**Comment by kisaacs** [comment]
Thanks Dinu and sorry to create all of that extra work for you. We were scrambling as I got assigned to this project rather late.

**Comment by sandarumk** [comment]
Merge reverted. Unfortunately the damage having the master branch's merge commits in the develop branch cannot be reverted without rewriting the history which is not recommended in public repos.

**Pull request merged**
