### PR TITLE
Fixes #438 : Resolved ambiguous title issue in ConfidentialityFragment

### LINKED ISSUE #438: Bug in ConfidentialityFragment
View is Ambiguous. Title is Displayed Twice in the Dialogue. 

screenshot_2017-03-12-23-53-02

screenshot_2017-03-12-23-53-05

screenshot_2017-03-12-23-53-11

@sandarumk 
If this Bug is valid. I would like to work on this.
Thank you :)

### PR DESCRIPTION
**Pull request by pandilladivya**
Ref #438 

@sandarumk 
Kindly Review..

The Following is the Screenshot.
screenshot_2017-03-14-22-56-42

### CODE REVIEW

**Comment by abs51295** [comment]
@pandilladivya Are you able to run it on 7.0 with this modification?

**Comment by abs51295** [comment]
@pandilladivya I think it's better to add ` getDialog().requestWindowFeature(Window.FEATURE_NO_TITLE);` line also so that there is no blank space in the dialog for title. You can refer this [SO question](http://stackoverflow.com/questions/15277460/how-to-create-a-dialogfragment-without-title/15279400).

**Comment by pandilladivya** [comment]
@abs51295 
Thank you for the suggestion :)
I think removing this line would be suffice .
```
 getDialog().setTitle(title);
```

Because  if we add this
```
 requestWindowFeature(Window.FEATURE_NO_TITLE);
```

The App would crash for API 21.

**Comment by abs51295** [comment]
I don't think then application would crash on API 21. Could you please tell me the reason?

**Comment by pandilladivya** [comment]
@abs51295 

I'm sorry for not being clear.
I happened to try this .. and unfortunately there was an application crash.
I din't yet research on it. But yes, there is always a way to fix it.

ref: http://stackoverflow.com/questions/21354365/android-requestwindowfeaturewindow-feature-no-title-exception . (Similar case)

But.. for this issue I think removing that line would do because we are explicitly setting the title over there.
I don't think we should complicate things when there is a simpler solution. :)

Thanks.

**Comment by abs51295** [comment]
The question you are pointing to is not the same issue because we are using a Custom dialog by extending `DialogFragment` class and I have tried it and it works fine.

Secondly, obviously the issue is resolved by adding that line but the title space is not removed from the dialog which should be removed if we are not using a title.

Thirdly, adding a single line wouldn't complicate the issue. Instead I think it's​ a good practice to explicitly set the dialog to not use a title so that there would be no similar issues in the future. 

This is just my view on the issue. You can wait for @sandarumk to review this pull request.

**Pull request merged**
