### PR TITLE
Fixed Inconsistent alignment of TextView

### PR DESCRIPTION
**Pull request by pandilladivya**
@sandarumk 

This PR is in accordance with #294 

Here is the screenshot of the updated one!

screenshot_2016-11-17-22-10-06

Kindly Review
Thank You :)

### CODE REVIEW

**Comment by pandilladivya** [comment]
@sandarumk 

Kindly review #298 
Thank You!

**Comment by rohands** [comment]
@sandarumk you merged it into master branch?

**Comment by sandarumk** [comment]
@rohands oh shit. Yes. I will revert it. Didn't see that coming.

**Comment by sandarumk** [comment]
Reverted. Please send the PR to the develop branch

**Comment by pandilladivya** [comment]
@sandarumk 
Sorry,I didn't notice..
Will send a PR right away!

**Pull request merged**
