### PR TITLE
changed signup and Navbar UI

### PR DESCRIPTION
**Pull request by ramit0402**

### CODE REVIEW

**Comment by ramit0402** [comment]
@sandarumk Please review the PR and let me know if any changes are required. 
PR #382
screenshot_2017-02-25-12-27-30
screenshot_2017-02-25-12-26-30
screenshot_2017-02-25-12-26-56
screenshot_2017-02-25-12-27-24

**Comment by sandarumk** [comment]
What is the related issue?

**Comment by ramit0402** [comment]
In the Signup activity the spinner used a custom drop-down menu which were not following the guidelines of googles material design as the spinner_item had a layout width of wrap_content while the Spinner width was match_parent. The material design also suggests the nav-bar color to be on the similar lines as the app theme

**Comment by ashu-dadhich** [comment]
Hi @ramit0402 what she meant was the corresponding issue related to this PR.
Please follow the guidelines as mentioned in the links below.
https://github.com/systers/FirstAide-Android/wiki/Issue-Reporting-Best-Practices
https://github.com/systers/FirstAide-Android/wiki/PR-Best-Practices

**Comment by sandarumk** [comment]
We are currently not looking for any UI changes. If you have another issue, please go through the guidelines and report. Then we can discuss the fix there.

**Pull request closed without merging**
