### PR TITLE
Code Optimization

### PR DESCRIPTION
**Pull request by sethbrudee**
Fix for issue #176 (Code optimization)

### CODE REVIEW

**Comment by sandarumk** [comment]
You have committed files which shouldn't be committed. Remove them.

**Comment by sethbrudee** [comment]
Okay, sorry about that. I'll make the corrections

**Comment by calistus** [comment]
To avoid such mistake in future, add those files to your .gitignore.

**Comment by rohands** [comment]
@sethbrudee Just a suggestion. You can check out projects from VCS in Android Studio, this lets you commit the required files, directly push and switch to branches without having to type the commands. I'm using it currently and I feel it definitely makes one's life easy :)

**Comment by sethbrudee** [comment]
Thanks @rohands, but that is what I used. I just made a mistake of committing the files

**Pull request closed without merging**
