### PR TITLE
Update comments

### PR DESCRIPTION
**Pull request by yogeshbalan**
Updated the comments according to the template described in the issue #94 for reporting sub-module.

### CODE REVIEW

**Comment by sandarumk** [comment]
Limit this to one commit. Get rid of merge commits. A quick google search will show you how.

**Comment by sandarumk** [comment]
Check the class comments too. They are not according to the template. And when you are adding comments to the methods you have missed some @params comments as well.

**Comment by yogeshbalan** [comment]
The class comments needs `@since` attribute. Do I need to check the date of class creation from commit history.

**Comment by sandarumk** [comment]
Yes if it is already not there

**Pull request closed without merging**
