### PR TITLE
Edit on Opening and Running App in Android Studio

### PR DESCRIPTION
**Pull request by ivan-claire**

### CODE REVIEW

**Comment by sandarumk** [comment]
Don't make multiple commits to a small change.

**Comment by ivan-claire** [comment]
okay Dinu, was a mistake

**Comment by sandarumk** [comment]
Can you please make this into one commit? A quick google search will tell you how.

**Comment by sandarumk** [comment]
And please resolve the conflicts too.

**Comment by ivan-claire** [comment]
okay, I'll do just that

**Comment by sandarumk** [comment]
Any updates on this?

**Comment by ivan-claire** [comment]
@sandarumk Can I create a new pull request with just one commit and no conflicts?

**Comment by ivan-claire** [comment]
I'm ready to create the pull request now, if its okay.

**Comment by sandarumk** [comment]
Yeah sure. Close this when you send the new one.

**Pull request closed without merging**
