### PR TITLE
issue #369 resolved

### PR DESCRIPTION
**Pull request by getsanjeev**
Shifted the username check to splashActivity.

### CODE REVIEW

**Comment by m-murad** [comment]
@getsanjeev 
don't include `app/app.iml` file in your commit

**Comment by getsanjeev** [comment]
@free4murad I dont understand why app/app.iml gets added , when *.iml has been included in gitignore.

**Comment by getsanjeev** [comment]
@sandarumk I dont understand why app/app.iml gets added , when *.iml has been included in gitignore.

**Comment by m-murad** [comment]
@getsanjeev 
from what I know (I might be wrong)
The line `*.iml` in `.gitignore` will only ignore the `.iml `files that are in the root directory of the project.
for ignoring all `*.iml` files we have to add `/*/*.iml` to the `.gitignore` file.

@sandarumk 
Please correct me if I am wrong.

**Comment by getsanjeev** [comment]
removed extra files, have a look.

**Comment by getsanjeev** [comment]
@sandarumk removed extra files. Please review it.

**Comment by sandarumk** [comment]
When you are fixing an issue please mention the issue id in the comments too so the issue can be linked here. #369

**Pull request merged**
