### PR TITLE
Fixed the transitions

### PR DESCRIPTION
**Pull request by rishimadhok**
This is in reference to issue #275. I have fixed this issue. The transitions are as expected now.

### CODE REVIEW

**Comment by sandarumk** [comment]
All the down and up transitions should be removed. Please read the Patrick's last comment on the issue and do the necessary changes,

**Comment by chamika** [comment]
@rishimadhok 
It is better to avoid code duplicates. So try to refactor in following way.

`int inAnim = R.anim.push_down_in;`
`int outAnim = R.anim.push_down_out;`
`if(TAG.equals(ContactOtherStaff.TAG)){`
`  inAnim = R.anim.fade_in;`
`  outAnim = R.anim.fade_out;`
`}`
`fragmentManager.beginTransaction()`
`  .setCustomAnimations(inAnim,outAnim,R.anim.fade_in,R.anim.fade_out)`
`  .replace(R.id.fragment_container, fragment,TAG)`
`  .addToBackStack(TAG)`
`  .commit();`

**Comment by sandarumk** [comment]
@rishimadhok are you still on this?

**Comment by rishimadhok** [comment]
@sandarumk yes maam I will do the needful as soon as possible.

**Comment by sandarumk** [comment]
@rishimadhok any updates?

**Comment by sandarumk** [comment]
Closing the PR and reserving the issue for GCI since the assignee has not responded proactively about the fixes suggested.

**Pull request closed without merging**
