### PR TITLE
Solved Resources validation Lint Errors

### PR DESCRIPTION
**Pull request by pandilladivya**
@sandarumk 

Solved **Resorces validation** Lint errors

Removed these three issues...

captureee

Kindly review!
Thank You.

### CODE REVIEW

**Comment by pandilladivya** [comment]
@sandarumk 

There are three Lint errors in **Android Resources Validation**

image

Since **FAQFragment** is not assignable to **android.app.Activity** we are getting an error in Manifest file. To Fix this Lint error, I've converted FAQFragment into activity and didnot change any of its functionality  and have taken care of all possible test cases.
Second and third are also fixed. 

Kindly review
Thank You :)

**Comment by rohands** [comment]
@pandilladivya There is a reason why FAQFragment and many other classes are kept as fragments here. Please refrain from changing architecture of the app. 
What you did sure is a workaround but I'd suggest keeping FAQFragment as a Fragment. 
I think all you have to do is remove the code which causes error in the Manifest File and it would work just fine. Since there is no need to explicitly mention classes in the manifest file unless they are being invoked by an intent.

**Comment by pandilladivya** [comment]
@rohands 

The following is the screenshot of the **lint issue** which I need to fix.

image

This error is occurred because **FAQFragment** is a *fragment* but not a *class* and it is mentioned in Manifest file.

image

There are two ways to solve this error.
- Convert the fragment into a class.
- Add a suppress Tag to the issue

But **suppressing the lint issue** is not a fix. @sandarumk also informed me the same.
So to fix the lint issue i had to convert the fragment into class.
I thought removing code is not the appropriate fix so i converted the fragment into class
If you are okay with removing code...I will do it right away :)

Kindly review!
Thank you :)

**Comment by rohands** [comment]
I don't seem to understand what you mean by <i>This error is occurred because FAQFragment is a fragment but not a class and it is mentioned in Manifest file.</i>
The error occurs because it's not an activity but it's still mentioned in the Manifest file.

**Comment by pandilladivya** [comment]
I'm really sorry @rohands 
Typo error
This error is occurred because FAQFragment is a fragment but not an **Activity** and it is mentioned in Manifest file.

**Comment by pandilladivya** [comment]
@rohands @sandarumk 
Kindly review #301 

Thank You!

**Comment by sandarumk** [comment]
@pandilladivya , @rohands is correct. In fact what you have to do is remove the code from the Manifest file.

**Comment by sandarumk** [comment]
@pandilladivya Please close a PR if you are fixing the assigned issue in another PR.

**Comment by sandarumk** [comment]
duplicate #301

**Pull request closed without merging**
