### PR TITLE
Code Optimization - excluding commits

### PR DESCRIPTION
**Pull request by sethbrudee**
Fix for issue #176 (Code optimization) - excluding commits

### CODE REVIEW

**Comment by sandarumk** [comment]
Why does it shows the Files Changed as 0?? That is a large number of commits for a small optimization. Please get rid of merge commits since they are not needed for the PR (not needed for our repository). Do a fresh commit and send the PR. or else you can squash them. But still files changed should show the diff.

**Comment by sandarumk** [comment]
If you are sending a fresh PR always remember to close your older one.

**Comment by rohands** [comment]
https://github.com/blog/2141-squash-your-commits could help

**Comment by sethbrudee** [comment]
Okay. Files changed as 0, I guess it's because I pushed changes without changing previous commits.

I'll make amendments. Thank you

**Comment by sethbrudee** [comment]
@sandarumk I have understood your comment in this current pull request, but as regards the previous one still on the same topic (Code Optimization), I don't really understand which files you said I shouldn't commit. Are they the additional files created by Android studio, or the Java files I contributed to, or both? Thank you.

**Comment by sandarumk** [comment]
Android studio files. A quick google search will give you more ground on this.

**Pull request closed without merging**
