### PR TITLE
#338 App crash in Intro Slides - "Done" Textview Bug solved

### PR DESCRIPTION
**Pull request by codingblazer**
#338 As discussed in the issue making "Done" Textview unclickable (just for indication that user is done with intro slides).

### CODE REVIEW

**Comment by sandarumk** [comment]
@codingblazer your commit messages should be improved. If you do a quick google search you will find many good articles.

**Comment by codingblazer** [comment]
@sandarumk Its great to learn such things from you people. I have gone through these articles [1](https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message) [2](http://chris.beams.io/posts/git-commit/) [3](http://who-t.blogspot.in/2009/12/on-commit-messages.html)
What I have understood is -
1. Specify issue no. , what is it adressing, files effected, why is it needed, How you addressed the problem.
2. Sometimes it may need to break commit message in subject and body (separated by blank line) and explaining fix in body.

> Fixes #338 - App Crashes when user clicks Done in Last CircleIntro Slide
> 
> Removed unnecessary onClick in layout of Last CircleIntro Slide  which was causing crash

Please can you tell if this commit message could be better than this or if I am still missing anything. Thanks and please feel free to correct me on such things as they help me in learning :-)

**Comment by sandarumk** [comment]
Currently PCSA doesn't have a specified commit message standard. But in general the most projects have a standard and a template. In a way it is easy for the developers and reviewers since these templates/standards have all the information needed such as the information which you have mentioned. But in our case we just expect you to add a meaningful commit message. if you followed the approach you mentioned above, if the issue is a long one it will exceed the typical character length of a commit message. So you just have to add them accordingly. For this case, even a "Fix the app crash in CircleIntro Slide" would be okay. But what you have suggested is much better. But you have to keep in mind the length limitations.

**Comment by codingblazer** [comment]
@sandarumk I got it now. Thanks :-)

**Pull request merged**
