### PR TITLE
Get help now modified to match mockups

### PR DESCRIPTION
**Pull request by rohands**
Changes made to Get Help Now to match the new mockup
Static fragments changed to dynamic fragments. 
All changes related to get help now are now in a package called get_help_now

### CODE REVIEW

**Comment by sandarumk** [comment]
Can you post a screen shot of the Get Help Now screen?

**Comment by rohands** [comment]
Contact Post Staff Screen
whatsapp-image-20160701

**Comment by sandarumk** [comment]
Can't you make the bottom most message fully visible ?

**Comment by rohands** [comment]
It's a scroll view so that shouldn't be a problem
But do you want me to reduce the spacing between any of the elements?

**Comment by sandarumk** [comment]
Yes. It would look much better.  Otherwise the PR looks okay.

**Comment by rohands** [comment]
screenshot_2016-07-01-23-45-30

**Comment by rohands** [comment]
@sandarumk 
I've made the required changes and posted a screenshot above

**Pull request merged**
