### PR TITLE
Landscape UI Issues solved 

### PR DESCRIPTION
**Pull request by codingblazer**
#125 @sandarumk I have solved all issues except "Dialog Covering Status Bar" which was assigned to    @saketkumar95. However I have a fix for this too. I have created separate commits to make reviewing easy for you. I will squash them once you are done reviewing if you say so. You can find reasons for every changes I have made. Thanks :-)

### CODE REVIEW

**Comment by codingblazer** [comment]
I am listing all the issues as reported in #125 along with changes I have made to solve them -

1. **Progress bar not visible in splash** - Earlier margin from top was more than height available on landscape mode. I have decreased this margin so that it comes within the screen and shifted logo upward to have space for this progress bar (otherwise logo and progress bar will overlap).
**Layout will remain exactly same as earlier in portrait.**

2. **Circle of Trust in one screen as suggested in #102 -** I have made changes in UI as below. If you want to keep portrait UI unchanged, I can create separate XML just for landscape.<br>

- <p>Changes made - I moved edit_button at level of title (title and edit_button in horizontal linear layout) and added some paddingLeft to bring title again in center. Also I changed topmargin of top 2 comrades so that UI can be accommodated in landscape without any need of scroll. I used different dimen variable for this because it was been used at other places too and thus can't be changed.</p>

3. **Circle of Trust Intro Slides Partial UI in slide 1 and 2** - The layout weight needed to be adjusted for landscape because of less space available.

4. **Contact Post Staff alignment problem as discussed in #119** - I have made buttons of greater width in landscape so that it look like other buttons in app Ex- buttons in Other Post Staff. Also below buttons there is a textview that is now brought in center using gravity and match parent is done as gravity effect will be reflected only in that case.

5. **Contact Other Staff Buttons Heading not in Center** - Click any button in Contact Other Staff, heading is not in center => Gravity center is set and match parent width so that gravity can work.

6. **Services after Sexual Assault and Tactics** - Text boxes are now in center in landscape by setting required padding or margin resp.

7.  **Sign Up Activity partially visible** - Added Scrollview as root which allows user to scroll to the part that was not visible.

8. **Safety Plan Activity** - This was the most difficult task. There were 2 problems -

- Textview is of different size everytime (since amount of text is different in different tabs).This textview is put inside Viewpager of fixed height. The viewpager height is smaller than text and thus text is lost.Thus we need a scroll for textview. Also UI is bigger than screen and we need a scroll for it too.
There are multiple scroll and layout hierarchy is complex- Tab Viewpager ->Common Fragment-> Again Viewpager -> Custom textview -> Textview. Due to this scroll of android get confused and outer scroll never works resulting in loss of some part of UI.

- Solution - In Android, Scrollview inside scrollview can never work. So I reduced the height of Textview further so as to ensure that we will not need outer scroll ever and since now there is only one scroll needed, it will work great without any confusion for android.

9. **Radar Fragment** - Part of UI lost - Same solution as above used.

10. **Safety Plan Basics Activity** - Last Button lost - Added Scrollview.

**Comment by sandarumk** [comment]
Can you fix the merge conflict. It is because I fixed the redundant integer xml issue I guess.

**Comment by sandarumk** [comment]
I haven't fully reviewed your PR. So wait until I do so. Then you can do the changes (if any required) and then squash the commits. Squashing them to few seems good rather than to a single commit. Let's discuss that after I reviewed your PR.

**Comment by codingblazer** [comment]
@sandarumk Yeah sure. Please let me know when you are done reviewing :-)

**Comment by sandarumk** [comment]
Can you add screenshots of each screen you mentioned here. Also can you point out where the fix for the signup activity is(7)? It would have been much easier for the reviewers if you listed down the fixes with the order of screen transitions by the user.

**Comment by sandarumk** [comment]
screenshot_1485014661
Circle of trust is still scrollable in mine.

**Comment by codingblazer** [comment]
@sandarumk 
1. Will add screenshots in an hour.
2. Sorry, i forgot to push the commit for Signup Activity. Will do it soon.
3. By transition do you mean something like this - (Home Screen -> Get Help Now -> Contact Post Other Staff)
4. I will look into Circle of Trust problem.

**Comment by sandarumk** [comment]
From order of transitions I meant, signup activity comes to the top, then get help now, etc,..

**Comment by sandarumk** [comment]
Please fix the merge conflict as well

**Comment by codingblazer** [comment]
@sandarumk Yeah sure.

**Comment by codingblazer** [comment]
@sandarumk Can you please tell which device you tested on for Circle of Trust.

**Comment by sandarumk** [comment]
Nexus 5. But I am not sure whether the pR was checkedout correctly. That is why I asked you to add all the screen shots of the fixed screens. So we can verify that the issues are fixed.

**Comment by codingblazer** [comment]
@sandarumk I am on it.

**Comment by codingblazer** [comment]
1. **Splash Screen**  Progress bar not visible 

  =>  

2. **Sign Up Activity** Partial UI

 =>  

3. Get Help Now 

-> **Contact Post Staff** Buttons not in center

 =>  

-> **Contact Other Staff** -> PC saves... , Office of victim.., Office of Inspector...-> Heading not in center 

 =>  

 => 
 
 =>  

4. Circle of Trust 

-> **Intro slide 1 and 2** partial UI

 =>  

 => 
 
-> **Circle of Trust Screen** not accommodated completely      

 =>  

5. Safety Tools 

-> Radar -> **See Any Step** -> Partial UI 

 =>  

->**Tactics of Sexual Predators** -> The TextView Boxes should be in center            

 =>  

-> **Safety Plan Basics** -> last button not visible

 =>  

-> Safety Plan Basics -> **Purpose of safety.. or any other button** -> Dialog covers status bar
-> SafetyPlan -> **Home(same with any other tab)**-TextView not inside & UI not scrollable either.

 =>  

6. Support Services

->**Services after Sexual Assault** -The TextView Boxes should be in center

 =>  

->Confidentiality -> **Role of Staff (same with other 2 buttons)** -> Dialog Problem - To be solved by @saketkumar95

**Comment by codingblazer** [comment]
@sandarumk I have attached screenshots, added the commit for SignUp Activity, wrote the the flow in order (screenshots are in order) and resolved the merge conflict. Please review :-)

**Comment by sandarumk** [comment]
screenshot_1485099245
Can you check this screen with different screen sizes. I checked with three devices. One is HTC M7 mini (4.3-inch, 720x1280 ) which was different from this. But different from your screen shot too. 
Checked with Nexus S (4 inches, 480 x 800 pixels ) The result is the above screen shot.
Checked with Nexus 5 (4.95 inches , 1080 x 1920 pixels ) The result is fine.
So it appeared to be your fixes only work for a certain screen size. Can you fix that?

**Comment by codingblazer** [comment]
@sandarumk Yeah sure.

**Comment by sandarumk** [comment]
any updates?

**Comment by codingblazer** [comment]
@sandarumk I was travelling this week. Will update soon.

**Comment by sandarumk** [comment]
Sure.

**Comment by sandarumk** [comment]
Can you post the screenshots for Contact Post Staff for the 3 screen sizes I mentioned above?

**Comment by codingblazer** [comment]
@sandarumk Please check. I have tested on following devices -
Galaxy Nexus, Nexus One, Nexus S, Nexus 4, Nexus 5,Nexus 5X, Nexus 6, Nexus 6P, Nexus 7 Tab, Moto X Style. (These devices cover all screen devices as suggested by Google)

**Comment by codingblazer** [comment]
@sandarumk Yeah, just a minute.

**Comment by codingblazer** [comment]
@sandarumk 
screenshot_1485862111
Nexus One
screenshot_1485862254
Nexus 5
screenshot_1485862412
Galaxy Nexus (Equivalent to HTC M7)

**Comment by codingblazer** [comment]
@sandarumk I have currently used this approach - Set different dimensions for 4 standard size buckets - small, normal, large, xlarge by calculating resp ratio. If you want me to make different xml's for all screen sizes and dpi's , I can do it but that won't be effective.

**Comment by codingblazer** [comment]
@sandarumk #376 Fixed via 77dabe4. 
For settings activity, since PreferenceEditText was used, dialog was internal and thus I have to use configchanges in manifest.
For dialogs in Help Now, I have used the solution suggested [here](http://stackoverflow.com/questions/12433397/android-dialogfragment-disappears-after-orientation-change).

**Comment by sandarumk** [comment]
Can you check this too. 
screenshot_1486747502
The hamburger menu seems to be too long.

**Comment by sandarumk** [comment]
Contact post staff and contact other staff screens are inconsistent too.
screenshot_1486747977
screenshot_1486747982

**Comment by codingblazer** [comment]
@sandarumk Have you fetched the latest changes. In case you have , can you tell me the device you checked this on. 
And are all other screens reviewed ? It will be great if I can make all the changes in one go :-)

**Comment by sandarumk** [comment]
Nexus 5.

**Comment by sandarumk** [comment]
No other screens are not reviewed. I started from the home screen with hamburger menu and then moved to the get help now. So I only got the chance to review those two. From the coding perspective, the PR seems to be doing okay.

**Comment by codingblazer** [comment]
@sandarumk Yeah sure

**Comment by codingblazer** [comment]
@sandarumk Navigation Bar and Contact Post Staff should look fine now. Please review :-)

**Pull request merged**
