### PR TITLE
Shifted contents to come below the status bar 

### PR DESCRIPTION
**Pull request by pandilladivya**
@sandarumk 

This PR is in accordance with issue #287 
Kindly review.
Thank You :)

### CODE REVIEW

**Comment by rohands** [comment]
@pandilladivya Can you post screenshots from devices running Android KitKat and Lollipop? Just want to make sure the PR works fine for both.

**Comment by pandilladivya** [comment]
@rohands 
Sure will do it right away :)

**Comment by pandilladivya** [comment]
@rohands 

**Marshmallow**

capture


**Lollipop**

screenshot_2016-11-06-00-26-24


**Kitkat**

8568069049763781312-account_id 1

**Comment by rohands** [comment]
@pandilladivya great job! PR is good to go.

**Comment by pandilladivya** [comment]
Thank You :)

**Comment by sandarumk** [comment]
@rohands Thank you for reviewing.

**Pull request merged**
