### PR TITLE
Clicking OK button takes back to CircleOfTrust Activity.

### PR DESCRIPTION
**Pull request by yatna**
Clicking the OK button in Trustees.java activity edits the contacts, displays a toast and then finishes the activity and takes user back to CircleOfTrust.java activity.

### CODE REVIEW

**Comment by sandarumk** [comment]
Hi Yetna, This issue is reported and assigned to somebody. Please go through the issues list and make sure to go through the issue list and follow the correct procedure. Otherwise people who are already working on it will feel discouraged. You should always make sure to report an issue before making a pull request. I think I told you this with one of your earlier requests.

**Comment by sandarumk** [comment]
However since you already did this, I will keep this open and check with the assignee whether he/she has already done it. If not I will review and merge this.

**Comment by sandarumk** [comment]
Sorry Yatna, The other assignee has already done that. Meanwhile I checked the code. Yours is good. But the other PR contains error handling as well.

**Comment by yatna** [comment]
Yeah thats cool :-)

**Pull request closed without merging**
